/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHA = 15;
  /** RegularExpression Id. */
  int FUN = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"&\"",
    "\"cons\"",
    "\"car\"",
    "\"cdr\"",
    "\"!=\"",
    "\"atom\"",
    "\",\"",
    "<ALPHA>",
    "<FUN>",
    "\"!atom\"",
  };

}
